### ISSUE TITLE
Ability to get the ratings to be used in structured data for Google

### ISSUE THREAD

**Issue by NickdeK** [trustpilot/plugin-magento2#17]
There should be a block/helper that can be used to get the actual rating from Trustpilot to be used in the AggregateRating structured data on the page. At this moment there doesn't seem to be a way to get this data using this module.

**Comment by arunas-stonis** [comment]
It is possible. For example if you add `Product Reviews SEO` TrustBox to `Product` page it will automatically generate AggregateRating structured data on each product page. You can find more information at Trustpilot: https://support.trustpilot.com/hc/en-us/articles/231993108
