### ISSUE TITLE
unable to initialize settings in Magento 2.2 CE

### ISSUE THREAD

**Issue by pppwu** [trustpilot/plugin-magento2#21]
unable to initialize settings in Magento 2.2 CE

### Preconditions
Magento V2.2.2 Community
Single Store Mode

### Steps to reproduce
1. Enable `single store view`
2. Add Installation Key to trustpilot general settings
3. Try to access  TrustBox page

### Expected result
1. Installation Key will be displayed in text field after save
2. Trustbox can be set after save installation key.

### Actual result
1. Installation Key can't be saved , but the system return saved successful
![2019-02-23 4 23 21](https://user-images.githubusercontent.com/30168100/53283903-aa5f5d80-3787-11e9-8876-3a490dfa6b79.png)

2. Trustbox Page can't be accessed
3. key record have been successfully inserted to DB  
`SELECT * FROM core_config_data WHERE path = 'trustpilotGeneral/general/key'`  
![2019-02-23 4 31 02](https://user-images.githubusercontent.com/30168100/53283967-70db2200-3788-11e9-87db-558f3c468be4.png)

**Comment by VitaVal** [comment]
Hi, pppwu
Thank you for reporting the issue.
Trustpilot has released a new plugin for Magento 2 integration.
It is not on the marketplace yet, but you can get it through Composer: https://support.trustpilot.com/hc/en-us/articles/203934298-Trustpilot-s-free-Magento-plugin-download-install-and-configure-it#download-install-plugin-via-composer

Let us know if you have other questions. 
Regards,
Trustpilot Team

**Comment by pppwu** [comment]
Hi @VitaVal  
But I have installed through composer, seems that configuration still can't be modified in single store mode.

![2019-03-06 5 29 00](https://user-images.githubusercontent.com/30168100/53870533-639a1f00-4035-11e9-9584-17bbd98068a3.png)


BR,
Peter
