### ISSUE TITLE
Can only save to scope_id of 1

### ISSUE THREAD

**Issue by shaggywolfhound** [trustpilot/plugin-magento2#22]
It seems that no matter what I set the scope to in Magento when I save the Integration key it only ever saves to scope_id=1 in the database under core_config_data.  

I need to be able to set this by store since I have 6 all with a different customer base and as a result different Trustpilot accounts.

**Comment by smuzza** [comment]
I can confirm this is also an issue.

Anyone from the Trustpilot team able to give an update?

**Comment by pppwu** [comment]
I think this issue is also related to https://github.com/trustpilot/plugin-magento2/issues/21, please help to make it compatible with **single-store mode** (scope_id=0).

**Comment by bossalinie** [comment]
I can confirm this also an issue.
It is impossible to configure the extension on multi-store modules with different settings.

**Comment by martijnrmediact** [comment]
Can we get an update on the status of this task, it is really imported to have this fixed for us.

**Comment by vilgro** [comment]
We've released new version. It should fix the issue
