### ISSUE TITLE
Undefined index: SERVER_PORT when entering store config section in backend

### ISSUE THREAD

**Issue by nrunde** [trustpilot/plugin-magento2#27]
`1 exception(s):
Exception #0 (Exception): Notice: Undefined index: SERVER_PORT in /var/www/html/vendor/trustpilot/module-reviews/Block/System/Config/Admin.php on line 31

Exception #0 (Exception): Notice: Undefined index: SERVER_PORT in /var/www/html/vendor/trustpilot/module-reviews/Block/System/Config/Admin.php on line 31
#0 /var/www/html/vendor/trustpilot/module-reviews/Block/System/Config/Admin.php(31): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/html/v...', 31, Array)
#1 /var/www/html/generated/code/Trustpilot/Reviews/Block/System/Config/Admin/Interceptor.php(24): Trustpilot\Reviews\Block\System\Config\Admin->getIntegrationAppUrl()
#2 [internal function]: Trustpilot\Reviews\Block\System\Config\Admin\Interceptor->getIntegrationAppUrl()
#3 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/trustpilot/module-reviews/view/adminhtml/templates/system/config/admin.phtml(9): Magento\Framework\View\TemplateEngine\Php->__call('getIntegrationA...', Array)
#5 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#6 /var/www/html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Trustpilot\Reviews\Block\System\Config\Admin\Interceptor), '/var/www/html/v...', Array)
#7 /var/www/html/generated/code/Trustpilot/Reviews/Block/System/Config/Admin/Interceptor.php(284): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#8 /var/www/html/vendor/magento/framework/View/Element/Template.php(301): Trustpilot\Reviews\Block\System\Config\Admin\Interceptor->fetchView('/var/www/html/v...')
#9 /var/www/html/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#10 /var/www/html/vendor/trustpilot/module-reviews/Block/System/Config/Admin.php(76): Magento\Backend\Block\Template->_toHtml()
#11 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field.php(77): Trustpilot\Reviews\Block\System\Config\Admin->_getElementHtml(Object(Magento\Framework\Data\Form\Element\Text))
#12 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Field.php(51): Magento\Config\Block\System\Config\Form\Field->_renderValue(Object(Magento\Framework\Data\Form\Element\Text))
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Block\System\Config\Form\Field->render(Object(Magento\Framework\Data\Form\Element\Text))
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Trustpilot\Reviews\Block\System\Config\Admin\Interceptor->___callParent('render', Array)
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Trustpilot\Reviews\Block\System\Config\Admin\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\Data\Form\Element\Text))
#16 /var/www/html/generated/code/Trustpilot/Reviews/Block/System/Config/Admin/Interceptor.php(143): Trustpilot\Reviews\Block\System\Config\Admin\Interceptor->___callPlugins('render', Array, Array)
#17 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(460): Trustpilot\Reviews\Block\System\Config\Admin\Interceptor->render(Object(Magento\Framework\Data\Form\Element\Text))
#18 /var/www/html/vendor/magento/framework/Data/Form/Element/Text.php(41): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#19 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(474): Magento\Framework\Data\Form\Element\Text->getHtml()
#20 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(86): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#21 /var/www/html/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(66): Magento\Config\Block\System\Config\Form\Fieldset->_getChildrenElementsHtml(Object(Magento\Framework\Data\Form\Element\Fieldset))
#22 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(460): Magento\Config\Block\System\Config\Form\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#23 /var/www/html/vendor/magento/framework/Data/Form/Element/AbstractElement.php(474): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#24 /var/www/html/vendor/magento/framework/Data/Form.php(329): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#25 /var/www/html/vendor/magento/framework/Data/Form.php(344): Magento\Framework\Data\Form->toHtml()
#26 /var/www/html/vendor/magento/module-backend/Block/Widget/Form.php(101): Magento\Framework\Data\Form->getHtml()
#27 /var/www/html/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(15): Magento\Backend\Block\Widget\Form->getFormHtml()
#28 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#29 /var/www/html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Form), '/var/www/html/v...', Array)
#30 /var/www/html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#31 /var/www/html/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#32 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Backend\Block\Template->_toHtml()
#33 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /var/www/html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#35 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#36 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#37 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#38 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(508): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#39 /var/www/html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(28): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#40 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#41 /var/www/html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/var/www/html/v...', Array)
#42 /var/www/html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#43 /var/www/html/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#44 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Backend\Block\Template->_toHtml()
#45 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#46 /var/www/html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#47 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#48 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#49 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
#50 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...', false)
#51 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#52 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#53 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#54 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#55 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#56 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#57 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#58 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#59 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#60 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...', false)
#61 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#62 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#63 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#64 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', false)
#65 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col', false)
#66 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#67 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#68 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#69 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#70 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#71 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#72 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#73 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#74 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', false)
#75 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#76 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#77 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#78 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#79 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#80 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#81 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#82 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#83 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#84 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', false)
#85 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#86 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#87 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#88 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#89 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#90 /var/www/html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#91 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#92 /var/www/html/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#93 /var/www/html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#94 /var/www/html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#95 /var/www/html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#96 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#97 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#98 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#99 {main}`

**Comment by arunas-stonis** [comment]
The issue was fix. https://github.com/trustpilot/plugin-magento2/commit/f368a38d6162c6f46437021babad7220a46f350b Thank you!
