### ISSUE TITLE
Multisite different shop url (per store view) TrustBox cannot be drag'n'dropped

### ISSUE THREAD

**Issue by bst2002git** [trustpilot/plugin-magento2#28]
Magento 2.3.1

Primary having different url per store_view does not allow to have Landig-Page in TrustBox-Preview
while default Magento has 'x-frame-options' => 'SAMEORIGIN',
I'v i change this, now i can see the Landing-Page but cannot drag'n'drop TrustBoxes, the "Not-Allowed" symbol appears.
Cross-Origin Request Blocked?

**Comment by dukeimg** [comment]
Answered in #26
