### ISSUE TITLE
Not see trustpilot menu in Magneto 2.2

### ISSUE THREAD

**Issue by mage2sol** [trustpilot/plugin-magento2#3]
I have install your extension but able to see trustpilot menu block in admin panel can you check please for magento 2.2

**Comment by aboswell** [comment]
mage2sol, We found the code in etc/adminhtml/system.xml to be the culprit. Change all instances of
`showInDefault="0" showInWebsite="1" showInStore="0"`
to
`showInDefault="1" showInWebsite="1" showInStore="1"`

There are three that I can see. Once you do and you flush cache, you should be able to see it.

**Comment by vdabar** [comment]
mage2sol, all you need to do is just to change your shop configuration scope to website. We also added message to unsupported scopes to make it easier to understand. https://github.com/trustpilot/plugin-magento2/commit/943ae53b98cf99e34caf589fec635dab871224de
