### ISSUE TITLE
Configuration page coming blank in store view

### ISSUE THREAD

**Issue by amrit-stream** [trustpilot/plugin-magento2#33]
Configuration page in admin coming blank when I changed the store. In the console, it is giving the admin.js error "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" on line 178 for sendSettings function.

**Comment by vdabar** [comment]
Hey, @amadacs, can you give us the value of "data-configuration-scope-tree" in your Magento configuration page? You can do that by Navigating to the configuration that doesn't work -> Right click -> View Page Source -> find "data-configuration-scope-tree" -> copy value.

**Comment by amrit-stream** [comment]
Hi, In page source I am getting this much data <div tabindex="0">
    <iframe
        src='http://ecommscript-integrationapp.trustpilot.com'
        id="configuration_iframe"
        frameborder="0"
        scrolling="no"
        width="100%"
        height="1400px"
        data-plugin-version='2.6.417'
        data-source='Magento2'
        data-version='Magento2-2.2.6'
        data-page-urls='

**Comment by vdabar** [comment]
@amrit-stream I see, maybe you can also send us logs of your system ?

**Comment by amrit-stream** [comment]
Hi, Thanks @vdabar but I have solved this issue. I have added **ini_set('memory_limit', '-1');** in index file. So now it worked.

**Comment by vdabar** [comment]
@amrit-stream ok, cool! I close the issue then :)
