### ISSUE TITLE
Font Awesome Toggle

### ISSUE THREAD

**Issue by webamondo** [trustpilot/plugin-magento2#35]
We are looking at performance improvements of our site which includes reducing the number of third party requests. We've noticed that font awesome comes bundled as default with trustpilot. From what I can see if you just use this module to send order data to trustpilot you don't need font awesome? In this case it would be good if you could toggle font awesome on and off via the admin? What does font awesome actually do for this module?

**Comment by vilgro** [comment]
It's fixed with release  2.6.430
