### ISSUE TITLE
Performance issues due to cache cleaning

### ISSUE THREAD

**Issue by hnsr** [trustpilot/plugin-magento2#40]
In a project of ours we have been experiencing issues with page load times, cache lock timeouts ever since we upgraded to 2.6.437. 

The cause seems to be the reinitableconfig->reinit() call in `\Trustpilot\Reviews\Helper\Data::getConfig` that was added in https://github.com/trustpilot/plugin-magento2/pull/39

I am unsure why this is needed so I don't how to properly fix this. For our project we simply patched away the reinit() call as a workaround, but I guess it was added for a reason

**Comment by wintermute-84** [comment]
This makes it unusable on magento 2.3
Cache is locked die to the pure code implementation.

**Comment by arunas-stonis** [comment]
Issue was fixed in the newest release 7a8504a. Thank you for reporting it!

**Comment by hnsr** [comment]
Great to hear, thanks!

Op do 29 aug. 2019 12:18 schreef arunas-stonis <notifications@github.com>:
