### ISSUE TITLE
The store that was requested wasn't found.

### ISSUE THREAD

**Issue by mateuszbereszczuk** [trustpilot/plugin-magento2#43]
I've installed the module but when I try to access it I get this error
<pre>1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The store that was requested wasn't found. Verify the store and try again.

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The store that was requested wasn't found. Verify the store and try again.

#1 Magento\Store\Model\StoreManager->getStore(1) called at [vendor/magento/module-catalog/Model/ResourceModel/Collection/AbstractCollection.php:96]

#2 Magento\Catalog\Model\ResourceModel\Collection\AbstractCollection->setStore(1) called at [vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php:591]

#3 Magento\Catalog\Model\ResourceModel\Product\Collection->setStore(1) called at [generated/code/Magento/Catalog/Model/ResourceModel/Product/Collection/Interceptor.php:128]

#4 Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor->setStore(1) called at [vendor/trustpilot/module-reviews/Helper/Data.php:208]
</pre>

There's a lot of stores in my project, and as far as I know, there's no store with an id of 1, why does the module try to access it?

**Comment by vdabar** [comment]
Sorry for late response, Issue was fixed in the newest release https://github.com/trustpilot/plugin-magento2/commit/3e488d04d2661c03b2f6e02d476e803cd18f1df0. Thank you for reporting it!
