### ISSUE TITLE
can't drug and drop trust boxes 

### ISSUE THREAD

**Issue by wintermute-84** [trustpilot/plugin-magento2#44]
Via magento admin can't drop trustboxes into iframe.
Iframe url is the same as storefront url.
Using latest 2.6.451, tried in chrome on mac and win, and safari, same result.
Magento 2.3.2

**Comment by vilgro** [comment]
@wintermute-84 Maybe there is some messages in console logs?

**Comment by arunas-stonis** [comment]
We released a fix for drag and drop in a new version 2.6.495
Please check commit: 5c8f684
