### ISSUE TITLE
Can't disable at store level after update.

### ISSUE THREAD

**Issue by shaggywolfhound** [trustpilot/plugin-magento2#48]
Used to be able to disable the extension at store level.  This no longer appears to be an option so we are sending invites to people that shouldn't be receiving them e.g. our amazon channel.  We now have all channels enabled where they shouldn't be.

This is really not acceptable.

**Comment by vdabar** [comment]
Hey, @shaggywolfhound, sorry for the late response. How did you disable it previously?

**Comment by vdabar** [comment]
Closed due to inactivity
