### ISSUE TITLE
Link for Product page for TrustBox is redirecting to admin

### ISSUE THREAD

**Issue by Tuuhea** [trustpilot/plugin-magento2#54]
Module version 2.6.478

Product page in the TrustBox is redirecting to admin page, when website scope is provided to getPageUrl method.

Seems that the strict comparison at https://github.com/trustpilot/plugin-magento2/blob/master/Helper/Data.php#L210 is failing because one is string and other is int.

This will cause the function not to find the provided website and causes it to return null.

**Comment by vdabar** [comment]
Hey, @Tuuhea, the problem should be fixed in https://github.com/trustpilot/plugin-magento2/commit/5c8f684ec17ac1b6ce2aad256e3057812a209ebc .
