### ISSUE TITLE
Adminhtml JS Source map comment breaks some admin sections

### ISSUE THREAD

**Issue by edward-simpson** [trustpilot/plugin-magento2#64]
https://github.com/trustpilot/plugin-magento2/blob/4aa36871bdac155a854b7bf044aaed30a6dcefcf/view/adminhtml/web/js/admin.min.js#L2

This line is causing adminhtml JS issues on some pages, when JS is merged

<img width="750" alt="Screenshot 2019-11-25 at 13 03 14" src="https://user-images.githubusercontent.com/26060776/69543151-e462c780-0f84-11ea-87df-f2dda9c70353.png">
<img width="750" alt="Screenshot 2019-11-25 at 13 03 26" src="https://user-images.githubusercontent.com/26060776/69543152-e4fb5e00-0f84-11ea-9133-3a4db86c7c73.png">
<img width="750" alt="Screenshot 2019-11-25 at 13 02 53" src="https://user-images.githubusercontent.com/26060776/69543150-e462c780-0f84-11ea-9cc3-645c2f8e87f5.png">

**Comment by wintermute-84** [comment]
I confirm this when js merge is enabled. 
You should use block comments in this sort of things.

`/**# sourceMappingURL=admin.min.js.map */`

**Comment by plainsdrifter** [comment]
Hi @edward-simpson. Thank you for letting us know.
It should be fixed with 2.6.524 release.

**Comment by fredden** [comment]
It looks like this was fixed in 2103b0a1d00d1cd982e54fafaa4d052f0f2139ff / #63.

**Comment by edward-simpson** [comment]
@fredden admittedly I haven't tested this yet, but from the looks of the commit all that's changed with this file is the removal of the new line at EOF, which doesn't _feel_ like it would fix the issue

Edit: Or maybe adding a new line at EOF, it's hard to tell from the commit actually, this could potentially solve it though
