### ISSUE TITLE
Upgrading to version 2.6.531 prevents category sorting from working

### ISSUE THREAD

**Issue by rob-aimes** [trustpilot/plugin-magento2#66]
## Description 
After upgrading to version `2.6.531` on this module on Magento `2.3.3`, the category sorting/filtering no longer appears to function correctly. As an example, sorting by price (ascending) functioned as expected before upgrading this module.

### Using version `2.6.524`

<details>
	<summary>Click here</summary>

![image](https://user-images.githubusercontent.com/29477517/72057667-a74d5d00-32c6-11ea-862a-3e1299552f67.png)

</details>

### Using version `2.6.531`

<details>
	<summary>Click here</summary>

![image](https://user-images.githubusercontent.com/29477517/72057520-72410a80-32c6-11ea-8e1f-cfa9eb91e54b.png)

</details>

------

As you can see from the above images, after upgrading to the latest version of this module, the sorting for products no longer functions. The order of display is the same regardless of any sorting applied.

**Comment by arunas-stonis** [comment]
The issue has been fixed in version 2.6.541.
