### ISSUE TITLE
TrustBox not generated for storeview with different domain

### ISSUE THREAD

**Issue by duckchip** [trustpilot/plugin-magento2#73]
Hi guys, 

We experiencing an issue with setting up Trustbox for a storeview that has a different domain defined.

Following error is thrown: 

```
Refused to display 'https://www.some-other-domain.com/?___store=fr' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
trustboxpreview.min.js:1 Uncaught DOMException: Blocked a frame with origin "https://www.default-domain.be" from accessing a cross-origin frame.
    at vn.value
```

module version: trustpilot/module-reviews                             2.6.542
magento version: 2.3.5

![ef9a3f5e-4816-4294-b462-8af5bfd6b15d](https://user-images.githubusercontent.com/9752966/88174344-6e525580-cc24-11ea-901e-86305c4ddbe6.png)

**Comment by duckchip** [comment]
@vilgro Any idea when this could be picked up?

Thanks!

**Comment by arunas-stonis** [comment]
It's unfortunate, you can't use drag and drop feature when admin and site domains missmatch or when on of (X-Frame-Options, Content-Security-Policy) headers are not allowing our plugin to load the site in iFrame. You might temporary disable these headers while setting up the plugin or you could add TrustBoxes manually.
