### ISSUE TITLE
Cookie blocking in Chrome update

### ISSUE THREAD

**Issue by DeLuuk** [trustpilot/plugin-magento2#75]
In the new Chrome update Chrome blocks all cookies that have SameSite as Lax defined.

All cookies coming from Trustpilot have this issue.
This is one of the messages you get in the devtools console:
```
A cookie associated with a cross-site resource at https://trustpilot.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

As far as I can see I have four cookies with this issue:
- __zlcmid
- ajs_anonymous_id
- ajs_user_id
- ajs_group_id

For if it matters for this bug, my Chrome version is 84.0.4147.105, I'm working with Magento 2.3.5-p2, PHP 7.3.20 and the version of the extension installed is 2.3.553 (the latest version on the Magento 2 Marketplace).

**Comment by arunas-stonis** [comment]
These are non essential cookies. Plugin will work without them. We will update them as soon as third party libraries will be updated (some of them was updated already). Thank you for reporting it!
