### ISSUE TITLE
In the backend config. When I login with it logs out it logs out immediately

### ISSUE THREAD

**Issue by Aquive** [trustpilot/plugin-magento2#91]
- I installed extension
- when I log in into the backend config with TP credentials, it succeeds
- Immediately it logs back out with a message which disappears. The message: Sorry, this email and password don’t go together. I can log in with success into TP business dashboard though.

What is the problem here? Something with the extension or with the account? I am waiting for support to answer my email. 

Magento version: 2.4.3
Trustpilot version: 2.6.564

**Comment by jorgb90** [comment]
Just a shitty build extension with no support here.

**Comment by Aquive** [comment]
@jorgb90 do you have the same problem?

In my case my adblockers were the problem.
